### ISSUE TITLE
Parou de funcionar

### ISSUE THREAD

**Issue by zeguil** [allugo/Frases-Livros-API#2]
Olá amigo, então creio eu que a API tenha dado algum problema

**Comment by saulojoab** [comment]
@zeguil olá amigo, o projeto foi descontinuado tem alguns anos e provavelmente o heroku matou o server, mas como o código é aberto sinta-se a vontade pra baixar ele e hostear em algum serviço :)

**Comment by zeguil** [comment]
Eu queria apenas sua base de dados se fosse possivel.

**Comment by saulojoab** [comment]
@zeguil 
A gente tava só usando esse JSON aqui: https://github.com/allugo/Frases-Livros-API/blob/master/utils/frases.json

Como eu disse, a gente planejava colocar muita frase, mas como foi descontinuado acabamos não colocando...
